### ISSUE TITLE
Bugs #8

### ISSUE THREAD

**Issue by zunath** [zunath/SWLOR_NWN#1451]
Tracking bugs found in revamp testing. New thread created as the old one was getting cluttered.

Bug ticket 1: https://github.com/zunath/SWLOR_NWN/issues/1130
Bug ticket 2: https://github.com/zunath/SWLOR_NWN/issues/1359
Bug ticket 3: https://github.com/zunath/SWLOR_NWN/issues/1380
Bug ticket 4: https://github.com/zunath/SWLOR_NWN/issues/1387
Bug ticket 5: https://github.com/zunath/SWLOR_NWN/issues/1396
Bug ticket 6: https://github.com/zunath/SWLOR_NWN/issues/1402
Bug ticket 7: https://github.com/zunath/SWLOR_NWN/issues/1421

**Comment by zunath** [comment]
Bug Report
The cloud effect from Bombs (Fire and Gas) do not damage the player who used them, allowing you to stand in clouds of fire and toxic gas. Epic as it is, might not be the best ;)

Bug Report
Fire/Gas Bombs from Devices do not do damage to anyone.

Bug Report
Incendiary bomb rank 1 does not seem to be doing any damage tested it on diffrent enermys

**Comment by zunath** [comment]
Bug Report
Sometimes in combat, using a heal/buff ability after targetting hostiles, it instead attacks the intended target of the buff/heal ability.

Bug Report
Using a med kit while in combat makes you attack who you use the medkit on.

**Comment by zunath** [comment]
Bug Report
Repeat quests of a specific type will show up as "Accepted" in the Hunters' Guild, despite not accepting them.

Bug Report
The agricultural guild is showing "Accepted" for quest I had completed prior to the last server reset, though it allows me to accept them again.

Bug Report
Possible this has already been reported. Tasks from guild masters do not update their status properly. For example if you have accepted and completed a Hunter task to take out X number of a creature it will still show ACCEPTED if it populates again and you don't have it in your quest log.

Bug Report
Some hunters quests are showing as accepted before even taking the quest, so on clicking into the quest as if to turn in the quest, it asks if you want to accept the quest, does not change to available by backing out.

**Comment by zunath** [comment]
Bug Report
Not sure if Force Stun is worked as intended. Force Stun III states that it effects 'all targets within 10m', however when I tested it on a group of 3, it appears to have applied to the first enemy on which my roll succeeded, then it jumped to a 2nd enemy, but my roll failed. It did not jump to the third enemy after that. Appears to be working as more of a chain than a 'effects all targets within 10m'.

**Comment by zunath** [comment]
Bug Report
While possessing an Jedi Temple Guard NPC I was unable to hear a Wookie player at all. I assume it's because the NPC doesn't know Shyriiwook, but I wasn't even able to hear the untranslated growling.

**Comment by zunath** [comment]
Bug Report
The Vellen Flesheaters in the Swamp drop the Coxxion Base map instead of the Swamp map.

The Western Swamplands or whatever it's called does seem to drop the correct map however.

**Comment by zunath** [comment]
QUEST ISSUES:

Bug Report
Issue : Quest not accepting.

Location : Hutlar.

NPC : Guylan Verruchi.

Summary : The quest given by Guylan regarding the power structures that have to be checked isn't accepting properly upon completion of the dialogue. Quest log doesn't update, system messages don't verify it's been accepted and the aforementioned power structures aren't interactable.

Bug Report
Hutlar power conduit quest doesn't activate when you talk to the quest-giver. The conversation happens as normal, but the journal doesn't update and the conduits can't be interacted with.

Bug Report
The avenging the captain quest on Veles does not give a reward if you choose the 'continue' option instead of one of the weapons

Bug Report
The quest 'Stuff Keeps Breaking!' demands 1 flawed leather, 1 flawed electronics and 1 agate. When I delivered the quest it said 'it requires 0 agate' and then ate all three items without giving mission completion.

Bug Report
Quests here still require repair kits with Farah that no longer exist.

Bug Report
The hunters guild gives a quest for 6x Mandalorian Polearm Parts and another one for 6x Mandalorian Blaster Parts. Several runs of the Mandalorian compound results in only drops of spears, pistols, and blaster rifles no parts, which don't count towards quest turn in. I believe the nessicary items have been removed from the loot table on rework.

Bug Report
Mandalorians do not seem to be dropping weapon parts such as vibroblades or blaster parts.

**Comment by zunath** [comment]
Bug Report
The 2nd level of vegetable patch doesn't seem to be spawning. I also would suggest that the swamp vines would share the same loot table or any loot table since they don't seem to have one?

**Comment by zunath** [comment]
Bug Report
Power attack doesnt seem to do anything. When attacking an enemy the accuracy was the same as when I had the setting off. So, I assume the damage might also be the same

Bug Report
Power Attack does not update DMG increase on the character sheet, and does not update hit chance on the combat log. Either it just doesn't display or doesn't work.

**Comment by zunath** [comment]
Bug Report
Using offensive abilities like double-shot and rocket do not break the stealth of the stealh field generator ability.

**Comment by zunath** [comment]
Bug Report
Re-applying Burst of Speed while you already have it, or waiting until it wears off, lowers your speed until you toggle dash back off and on.

Bug Report
When combining Dash with Burst of Speed movement speed effect and when Burst of Speed runs out one needs to disable and enable Dash in order to get the two to stack again.

**Comment by zunath** [comment]
Bug Report
Looted Mon Calan Seaweed of a Vegetable Patch on Hutlar.

**Comment by zunath** [comment]
Bug Report
For Althea: The use of Elven Race for her character pheno?

**Comment by zunath** [comment]
Bug Report
Dropped I Tattooine Desert Saga on Huttlar.

**Comment by zunath** [comment]
Bug Report
Character sits in "Chair, Chancellor" sideways.

![image](https://user-images.githubusercontent.com/3136227/178858812-cc7001e9-2fbe-4ea3-8c57-789918637a68.png)

**Comment by zunath** [comment]
Bug Report
Athena: Tried Subdual Mode on Sandra and It did not leave the player with 1HP, or dizzy..

**Comment by zunath** [comment]
Bug Report
A Pirate Ferron tried to ambush my ship. It could deal no damage to me, and when I flew close to it, it blew itself up.

Zun note: Make it so missile launchers cannot hurt their users when an NPC uses them.

Bug Report
Space combat: Still being hit by missiles despite 0% chance after the target is dead.

**Comment by zunath** [comment]
Bug Report
Mining Idailia Ore (t3 ore?) at piloting 24 does not give any XP.

**Comment by zunath** [comment]
Player attacked a DM and caused a server crash. No exception was logged.

**Comment by zunath** [comment]
Bug Report
Sometimes, Saberstaff's Circleslash ability hits the same enemy 3 times. Seems random, unable to replicate conditions reliably, but I am repeating it more than once.

**Comment by zunath** [comment]
Bug Report
After completing the quest "The Mandalorian Leader" I chose to claim the Captain Rifle as my reward. What I immediately noticed is the stats for it are actually worse than both the Titan Rifle and the Mandalorian Rifle which drops from within the facility you do the quest in. These weapon rewards need another look over because it's absolutely pointless to make them worse than vendor gear.

https://cdn.discordapp.com/attachments/998045449149751296/998045743266938960/Screenshot_2022-07-16_214334.png

https://cdn.discordapp.com/attachments/998045449149751296/998045743606681721/Screenshot_2022-07-16_214358.png

https://cdn.discordapp.com/attachments/998045449149751296/998045743917047828/Screenshot_2022-07-16_215259.png

**Comment by zunath** [comment]
Bug Report
Karrav Maubar in Tatooine MOA doesn't actually open a shop window after saying you want to shop.

**Comment by zunath** [comment]
Bug Report
Force Valor's and Battle Insight's buffs arn't appearing on buff bar when used? I use the skills and it goes on CD, but the icon for the buff of DR dosn't come up in the buff bar for Force Valor,, so, I'm not sure if I'm reciving the buff and theres no icon notification, or, if the buff isn't being applied. As far as Battle Insight, I receive the negitive effects, but, when I examine nearby party members they do not appear to be getting the +to evasion or attack, I think?

Bug Report
Force Valor does not add a buff icon next to your profile.

**Comment by zunath** [comment]
Bags empty weight was stuck at 6.0 after storing guild hunter task items (kath hound furs, mynock wings, etc) onto my starship directly from the bag.
Tried putting items back into bag and then moving them to regular inventory but the weight was still bugged. Then I sold the bag to get rid of it and now ALL vendors only sell a 6.0 weight bag.
I still have 1 bag with normal default weight in my inventory so it only seems to effect the bag I did starship storage from and now the vendors.

https://media.discordapp.net/attachments/1001154694825128017/1001154707194118255/20220719_112628.jpg

**Comment by zunath** [comment]
Unsure how to replicate -- however, numerous times now I have run into the issue where I will suddenly stop receiving ranged XP on kills, and Crippling Shot I will not activate. It will remain queued, but then be de-queued after 30 seconds or so, regardless of successful hits. Using devices / other weapons to get the kill gives XP as normal, with no ranged XP. Re-logging and restarting game does not fix, only re-slotting the bugged weapon in question.

**Comment by zunath** [comment]
The Korriban Sith crypt is very buggy, the ghosts get permenantly stuck in terrain quite often due to spawning inside of it. There are also invisible walls aplenty.

**Comment by zunath** [comment]
Players are able to speak while dead.

**Comment by zunath** [comment]
Bug Report
Cooking:

Increased credit rewards for guild requests weren't applied to agriculture quests (i.e. cooking).

**Comment by zunath** [comment]
Items can be used even after their charges reach zero

**Comment by zunath** [comment]
Bug Report
Quality doesn't cap at maximum quality. Can take the bar over the maximum value and the bar goes off the screen.

**Comment by zunath** [comment]
Bug Report
Saber throw I with Electroblade I not giving Force XP if it one-shots the enemy.

**Comment by zunath** [comment]
Bug Report
None of the tranquilizer shots work for my character

**Comment by zunath** [comment]
Bug Report
Permissions tabs in the starships are only showing blackness, they're currently not working. Got a screenshot of it. Relogging and restarting the game doesn't fix it and the issue seems to be affecting several people at the time not just me.

**Comment by zunath** [comment]
Bug Report
if you holocom while in space your holocom model is a space ship. awesome. maybe just deactivate the ability to recieve/send calls while piloting a ship.

**Comment by zunath** [comment]
STACKABLE ITEMS:

Bug Report
Intact Warocas Beak, Warocas Spine, Kath Hound Fur all do not stack.

**Comment by zunath** [comment]
Bug Report
Mon Cala:

Amphi-Hydrus just punch doing little damage.
Spreadsheet says they do force drain and electrical damage.

**Comment by zunath** [comment]
Bug Report
Harvesting Aracia Wood has a chance to give Ancient Wood instead. This should be changed, since even though they spawn in the same area, they're two different trees.

Area Name
Hutlar - Qion Tundra

**Comment by zunath** [comment]
Some have reported that even after last update, their APR remained high without the mastery perks.

**Comment by zunath** [comment]
2022-07-28 16:31:17.185 +00:00 [INF] C# Script 'mod_nui_event' threw an exception. Details: 

Exception type: System.NullReferenceException
Message       : Object reference not set to an instance of an object.
Stacktrace:
   at SWLOR.Game.Server.Service.GuiService.GuiPropertyConverter.ToJson(Object value) in C:\Projects\SWLOR_NWN\SWLOR.Game.Server\Service\GuiService\GuiPropertyConverter.cs:line 116
   at SWLOR.Game.Server.Service.GuiService.GuiViewModelBase`2.WatchOnClient[TProperty](Expression`1 expression) in C:\Projects\SWLOR_NWN\SWLOR.Game.Server\Service\GuiService\GuiViewModelBase.cs:line 289
   at SWLOR.Game.Server.Feature.GuiDefinition.ViewModel.PropertyPermissionsViewModel.Initialize(PropertyPermissionPayload initialPayload) in C:\Projects\SWLOR_NWN\SWLOR.Game.Server\Feature\GuiDefinition\ViewModel\PropertyPermissionsViewModel.cs:line 280
   at SWLOR.Game.Server.Service.GuiService.GuiViewModelBase`2.Bind(UInt32 player, Int32 windowToken, GuiRectangle initialGeometry, GuiWindowType type, GuiPayloadBase payload, UInt32 tetherObject) in C:\Projects\SWLOR_NWN\SWLOR.Game.Server\Service\GuiService\GuiViewModelBase.cs:line 256
   at SWLOR.Game.Server.Service.Gui.TogglePlayerWindow(UInt32 player, GuiWindowType type, GuiPayloadBase payload, UInt32 tetherObject, UInt32 uiTarget) in C:\Projects\SWLOR_NWN\SWLOR.Game.Server\Service\Gui.cs:line 337
   at SWLOR.Game.Server.Feature.GuiDefinition.ViewModel.PropertyItemStorageViewModel.<OnEditPermissions>b__73_0() in C:\Projects\SWLOR_NWN\SWLOR.Game.Server\Feature\GuiDefinition\ViewModel\PropertyItemStorageViewModel.cs:line 416
   at SWLOR.Game.Server.Service.Gui.HandleNuiEvents() in C:\Projects\SWLOR_NWN\SWLOR.Game.Server\Service\Gui.cs:line 236
   at SWLOR.Game.Server.Core.Internal.RunScripts(String script) in C:\Projects\SWLOR_NWN\SWLOR.Game.Server\Core\Internal.cs:line 143

**Comment by zunath** [comment]
2022-07-28 18:23:29.395 +00:00 [INF] C# Script 'mod_nui_event' threw an exception. Details: 

Exception type: StackExchange.Redis.RedisServerException
Message       : Syntax error at offset 31 near Gra
Stacktrace:
   at StackExchange.Redis.ConnectionMultiplexer.ExecuteSyncImpl[T](Message message, ResultProcessor`1 processor, ServerEndPoint server, T defaultValue) in /_/src/StackExchange.Redis/ConnectionMultiplexer.cs:line 1873
   at NRediSearch.Client.Search(Query q) in /_/src/NRediSearch/Client.cs:line 414
   at SWLOR.Game.Server.Service.DB.Search[T](DBQuery`1 query)+MoveNext() in C:\Projects\SWLOR_NWN\SWLOR.Game.Server\Service\DB.cs:line 284
   at SWLOR.Game.Server.Feature.GuiDefinition.ViewModel.PropertyPermissionsViewModel.Search() in C:\Projects\SWLOR_NWN\SWLOR.Game.Server\Feature\GuiDefinition\ViewModel\PropertyPermissionsViewModel.cs:line 323
   at SWLOR.Game.Server.Service.Gui.HandleNuiEvents() in C:\Projects\SWLOR_NWN\SWLOR.Game.Server\Service\Gui.cs:line 236
   at SWLOR.Game.Server.Core.Internal.RunScripts(String script) in C:\Projects\SWLOR_NWN\SWLOR.Game.Server\Core\Internal.cs:line 143


Zun note: This might be a data sanitization issue. Possible this is a player's name with an apostrophe or something

**Comment by zunath** [comment]
2022-07-28 16:23:34.642 +00:00 [INF] C# Script 'mod_nui_event' threw an exception. Details: 

Exception type: System.NullReferenceException
Message       : Object reference not set to an instance of an object.
Stacktrace:
   at SWLOR.Game.Server.Service.GuiService.GuiPropertyConverter.ToJson(Object value) in C:\Projects\SWLOR_NWN\SWLOR.Game.Server\Service\GuiService\GuiPropertyConverter.cs:line 116
   at SWLOR.Game.Server.Service.GuiService.GuiViewModelBase`2.Bind(UInt32 player, Int32 windowToken, GuiRectangle initialGeometry, GuiWindowType type, GuiPayloadBase payload, UInt32 tetherObject) in C:\Projects\SWLOR_NWN\SWLOR.Game.Server\Service\GuiService\GuiViewModelBase.cs:line 248
   at SWLOR.Game.Server.Service.Gui.TogglePlayerWindow(UInt32 player, GuiWindowType type, GuiPayloadBase payload, UInt32 tetherObject, UInt32 uiTarget) in C:\Projects\SWLOR_NWN\SWLOR.Game.Server\Service\Gui.cs:line 337
   at SWLOR.Game.Server.Feature.GuiDefinition.ViewModel.ManageStructuresViewModel.<OnManageProperty>b__62_0() in C:\Projects\SWLOR_NWN\SWLOR.Game.Server\Feature\GuiDefinition\ViewModel\ManageStructuresViewModel.cs:line 366
   at SWLOR.Game.Server.Service.Gui.HandleNuiEvents() in C:\Projects\SWLOR_NWN\SWLOR.Game.Server\Service\Gui.cs:line 236
   at SWLOR.Game.Server.Core.Internal.RunScripts(String script) in C:\Projects\SWLOR_NWN\SWLOR.Game.Server\Core\Internal.cs:line 143

**Comment by zunath** [comment]
Heavy armor:

Can't modify any part of the for Eclipse Armor (chest piece) like torso, etc.

The interface and sound look like it changes, but visually it doesn't.

**Comment by zunath** [comment]
Bug Report
When repairng the ship, the right corner display is not updating correctly. It will show the player off by one volley of repairs, while the person repairing will have the correct number.

Ie: Yurn repairs me for 15 and shows the ship at 16 hull while on Gra'ryyyr screen it shows me still at 1 hp. Untill I dock and refly which then it showes the correct number.


Zun note: Need to send out a refresh event whenever repairs are performed.

**Comment by zunath** [comment]
Bug Report
Quest "The Mandalorian Leader" not triggering completion for killing Mandalorian War Hero. Instance: Entered instanced room with another PC that has already completed the quest. First attempt I initiated combat, got first hit on the War Hero and did not get credit for the kill for the quest. Re-creation: Attempted again to try different circumstance and gain credit. Began combat again by attacking War Hero. War hero agroed to the other PC but I was the only one to do damage to them as well as got the kill. Still no quest credit. Cause of potential bug unknown. Was unable to continue testing. Only thought is that the other person in the instanced area had already completed the quest.

**Comment by zunath** [comment]
Bug Report
Enemies (mainly kath hounds) keep getting stuck at the very edge of the map, usually NW top-area. Cannot kill them since they're treated as being out of line of sight since they're on the very edge of the map.

Area Name
Viscara - Wildlands

**Comment by zunath** [comment]
Bug Report
Deflector Shield:

Spreadsheet says it lasts for 3-5 mins depending on rank.

Once the temporary hp is gone, the shield buff also disappears and it's over. Unlike in normal nwn,
where temporary max hp is kept for that duration. In otherwords, while the buff is active you can
heal up to the new max temporary hp even if you go under it.

Is it working as intended?


Zun note: I don't fully understand this one. Need to investigate.

**Comment by zunath** [comment]
Bug Report
Citizenship menu text is cut off no matter how far I extend the window. Screenshot attached.

![image](https://user-images.githubusercontent.com/3136227/181918238-69eb2d72-942b-47b6-888e-33b783996dcc.png)

**Comment by zunath** [comment]
Bug Report
Not always getting XP when using a Medpack to heal. I am fighting Sand Demons. When I do get XP, I get 950. My First Aid skill is 43. So, I should be getting aleast something. This was working before the server upgrade.
Area Name
Tatooine - Flatlands
Area Tag
TatooineAnchorheadFlatlands
Area Resref
tat_anc_flatlnd2

Per player: Med kit used during battle both during and after combat. Player was running around solo and tagging targets with their weapon prior to using the ability.

**Comment by zunath** [comment]
After receiving damage, the HP bar in the main screen depletes according to the amount of damage taken
However, when you rest after the encounter to regenerate your lost health, the HP bar does not show your HP increasing.
You can see your HP increasing in the character screen (C).

After resting and as the HP value still shows erroneous value, the HP bar updates to correct value either: if you take damage again or use a skill that affects your HP.


The HP bar of the HUD (where it lists HP STM FP) doesn't accurately track health. Character Sheet and the health bar next to my portrait does. Right now I have 230/230 HP but the HUD bar says 164/230


HP stops updating on the custom GUI panel when resting, but the HP is displayed correctly in the character sheet and next to my portrait. Transitioning to another area causes the custom gui HP to display correctly.

**Comment by zunath** [comment]
Bug Report
Tranquiliser Shot III does not work. The allies of the target who has been hit, despite being right next to him, continue acting normally against the advertised effect of the ability. To reproduce the issue, bunch up a group of melee-armed enemies and use the ability.

**Comment by zunath** [comment]
I accidentally logged out during a holocall and now I can't move, even after doing /endcall.

**Comment by zunath** [comment]
Bug Report
Logging in as a DM gives me player speed, not DM speed. This is fixed by immediately becoming a porg via ##SetAppearance 10035. Once again, porgs prove the masters of time and space.

**Comment by zunath** [comment]
Bug Report
Enemies keep aggroing through walls. This leads to them all rushing around to come try and gank me.

**Comment by zunath** [comment]
Bug Report
Battle Insight's description should be changed to alter "AB" to "Accuracy."

**Comment by zunath** [comment]
Descriptions of all evasion based abilities are using the raw AC value instead of the evasion value which is 5 times higher

**Comment by zunath** [comment]
Bug Report
Not sure how to replicate it, but I managed to use my harvester on a plagionite ore node when it was about 1/3 done mining to get multiple uses stacked up and mine it faster than intended

**Comment by zunath** [comment]
Bug Report
Neutral NPC's will attack players when players heal/buff the NPC's.

**Comment by zunath** [comment]
Bug Report
Shin part #142 and #143 are not evenly sized on the cathar body type. The left shin on both of these are smaller than the right.

**Comment by zunath** [comment]
Shirri A'Sar (The1Kobra) [QRHL4UNJ]
Bug Report
For some reason, shurikens are only getting 1 APR, even when I have throwing weapons mastery.
Area Name
Tatooine - North Mine Cliffs
Area Tag
anchor_entr_mine
Area Resref
tat_anc_nminecli
Position
(29.141638, 13.7421665, 29.141638)
Date Reported
2022-08-05 11:31:43
Player ID
0815f365-6d28-4111-bcaa-fae2da0b95a4

**Comment by zunath** [comment]
Genevieve Haught (Inkish) [QR64REMH]
Bug Report
Refinery just ate my ore

**Comment by zunath** [comment]
Bug Report
Frag Grenade can be used through walls. Enemies agro through the wall also.

In the Viscara - Mandalorian Facility, the hallways that is separated from the War Hero room by a wall, enemies can be agroed through the wall and then killed with grenades or any other "aoe" effect.

**Comment by zunath** [comment]
Bug Report
The exit of the cantina on Tatooin still exit ont the "old" map

**Comment by zunath** [comment]
Bug Report
Might already have been reported, but with DM-spawned ships (namely those spawned via DMFI tools) there's an issue where they often don't stop attacking after dying, even after their bodies despawn. Players have to transition to a new area in order to avoid being eventually killed.

**Comment by zunath** [comment]
Bug Report
Holocom allows you to call DM Avatars.

**Comment by zunath** [comment]
Provoke or some AOE effect aggro'd the entirety of the Mandalorian Facility, causing a TPK.

**Comment by zunath** [comment]
Forza Belt is mistakenly categorized under cloaks rather than belts.

**Comment by zunath** [comment]
Bug Report
Not a big issue, but got a message on Hutlar in the combat log that said "Its hot, and clouds are dotted around. Travels will be tiring - you should wear light clothing." Not sure if this can be removed as an option for Hutlar. Doesn't really fit.

**Comment by zunath** [comment]
Bug Report
repair hull module heals shield before it can heal hull. I believe it's not ment to heal the shield?

Zun note: Make sure this isn't just the auto shield regen

**Comment by zunath** [comment]
Bug Report
When I am over-encumbered, toggling the Dash ability off and on seems to remove my encumbered speed penalty entirely.
